language: go

sudo: false
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install make
        ;;
    esac

matrix:
  include:
  - os: linux
    go: "1.9.x"
  - os: windows
    go: "1.9.x"
  - os: linux
    go: "1.10.x"
  - os: windows
    go: "1.10.x"
  - os: linux
    go: "1.11.x"
    env:
      - GO111MODULE=off
  - os: windows
    go: "1.11.x"
    env:
      - GO111MODULE=off
  - os: linux
    go: "1.11.x"
    env:
      - GO111MODULE=on
  - os: windows
    go: "1.11.x"
    env:
      - GO111MODULE=on

install: make deps

script: make ci-test
